# Generated by Django 6.0.4 on 2026-05-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('En livraison', 'En livraison'), ('Livrée', 'Livrée')], default='En attente', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('co2_emission', models.FloatField()),
                ('price_total', models.FloatField()),
                ('client', models.ForeignKey(limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='logistics_core.product')),
            ],
        ),
    ]
