# Generated by Django 6.0.5 on 2026-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_deadline_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
