# Generated by Django 5.1.6 on 2026-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Tanger', 'Tanger'), ('Marrakech', 'Marrakech'), ('Agadir', 'Agadir'), ('Fès', 'Fès'), ('Oujda', 'Oujda'), ('Meknès', 'Meknès'), ('Kénitra', 'Kénitra'), ('Tétouan', 'Tétouan'), ('Dakhla', 'Dakhla'), ('Laâyoune', 'Laâyoune')], default='Casablanca', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Instructions spéciales de livraison', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
