# Generated by Django 5.1.6 on 2026-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_core', '0003_alter_product_id_alter_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rail',
            field=models.IntegerField(default=1, help_text='Aisle/Rack number'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.IntegerField(default=1, help_text='Shelf level'),
        ),
    ]
