# Generated by Django 5.1.6 on 2026-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_core', '0004_product_rail_product_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='total_rails',
            field=models.IntegerField(default=12),
        ),
    ]
