# Generated by Django 6.0.4 on 2026-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_core', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='total_shelves',
            field=models.IntegerField(default=8),
        ),
    ]
