# Generated by Django 6.0.4 on 2026-05-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Acceptée', 'Acceptée'), ('Terminée', 'Terminée')], default='Disponible', max_length=20)),
                ('distance', models.FloatField()),
                ('remuneration', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='client.order')),
                ('transporteur', models.ForeignKey(blank=True, limit_choices_to={'role': 'Transporteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(max_length=100)),
                ('capacity_m3', models.FloatField()),
                ('status', models.CharField(default='Actif', max_length=50)),
                ('transporteur', models.ForeignKey(limit_choices_to={'role': 'Transporteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
