# Generated by Django 5.1.6 on 2026-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.CharField(choices=[('Haute', 'Haute'), ('Normale', 'Normale'), ('Basse', 'Basse')], default='Normale', max_length=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='sequence_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='suggested_vehicle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Acceptée', 'Acceptée'), ('En transit', 'En transit'), ('Terminée', 'Terminée')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
