# Generated by Django 5.1.6 on 2026-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0002_mission_deadline_mission_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destination_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
