# Generated by Django 6.0.5 on 2026-05-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_order_id'),
        ('logistics_core', '0006_alter_product_id_alter_warehouse_id'),
        ('transporter', '0003_mission_destination_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('latitude_centre', models.FloatField()),
                ('longitude_centre', models.FloatField()),
                ('rayon_km', models.FloatField(default=15.0)),
                ('couleur_hex', models.CharField(default='#3B82F6', max_length=7)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='transporteur',
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('camionnette', 'Camionnette'), ('camion', 'Camion')], max_length=20)),
                ('immatriculation', models.CharField(max_length=20)),
                ('capacite_max_kg', models.FloatField(default=100.0)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En livraison'), ('pause', 'En pause'), ('hors_service', 'Hors service')], default='disponible', max_length=20)),
                ('latitude_actuelle', models.FloatField(blank=True, null=True)),
                ('longitude_actuelle', models.FloatField(blank=True, null=True)),
                ('total_livraisons', models.IntegerField(default=0)),
                ('total_co2_economise_kg', models.FloatField(default=0.0)),
                ('note_moyenne', models.FloatField(default=5.0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chauffeurs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporter.zone')),
            ],
        ),
        migrations.CreateModel(
            name='MissionLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('assignee', 'Assignée'), ('acceptee', 'Acceptée'), ('en_route_entrepot', 'En route vers entrepôt'), ('colis_pris', 'Colis récupéré'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Échec livraison')], default='assignee', max_length=30)),
                ('trajet_json', models.JSONField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('co2_estime_kg', models.FloatField(blank=True, null=True)),
                ('co2_mode_classique_kg', models.FloatField(blank=True, null=True)),
                ('co2_economise_kg', models.FloatField(blank=True, null=True)),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('note_client', models.IntegerField(blank=True, null=True)),
                ('commentaire_client', models.TextField(blank=True)),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporter.chauffeur')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.order')),
                ('entrepot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_core.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TourneeJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('trajet_optimise_json', models.JSONField(blank=True, null=True)),
                ('distance_totale_km', models.FloatField(default=0)),
                ('co2_total_kg', models.FloatField(default=0)),
                ('co2_economise_total_kg', models.FloatField(default=0)),
                ('statut', models.CharField(default='planifiee', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.chauffeur')),
                ('missions', models.ManyToManyField(to='transporter.missionlivraison')),
            ],
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
