# Generated by Django 5.1.6 on 2026-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stock_strategy',
            field=models.CharField(choices=[('DEMAND', 'Proximité Demande'), ('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('SPT', 'SPT (Shortest Processing)'), ('LPT', 'LPT (Longest Processing)')], default='DEMAND', max_length=10),
        ),
    ]
