# Generated by Django 5.1.6 on 2026-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_stock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_co2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_time',
            field=models.FloatField(default=0.0),
        ),
    ]
